[dev]
  port = 8888
  autoLaunch = false

[[redirects]]
  from = "/media/*"
  to = "http://localhost:3000/media/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "http://localhost:3000/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/admin-key"
  to = "http://localhost:3000/admin-key"
  status = 200
  force = true

[[redirects]]
  from = "/healthz"
  to = "http://localhost:3000/healthz"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "http://localhost:3000/index.html"
  status = 200
  force = true